<?php

namespace Database\Seeders;

use App\Models\encabezados_dets;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class Encabezados_DetSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            ['encabezados_id' => '1', 'nombre' => 'Cedula de Ciudadania', 'nomenclatura' => 'CC'],
            ['encabezados_id' => '1', 'nombre' => 'Permiso de Permanencia', 'nomenclatura' => 'PPT'],
            ['encabezados_id' => '2', 'nombre' => 'Activo', 'nomenclatura' => 'AC'],
            ['encabezados_id' => '2', 'nombre' => 'Inactivo', 'nomenclatura' => 'IN'],
            ['encabezados_id' => '2', 'nombre' => 'Pendiente', 'nomenclatura' => 'PD'],
            ['encabezados_id' => '2', 'nombre' => 'Revisado', 'nomenclatura' => 'RV'],
            ['encabezados_id' => '2', 'nombre' => 'Rechazado', 'nomenclatura' => 'RC'],
            ['encabezados_id' => '3', 'nombre' => 'Sin Anomalias', 'nomenclatura' => 'NA'],
            ['encabezados_id' => '3', 'nombre' => 'Bypass', 'nomenclatura' => 'BY'],
            ['encabezados_id' => '3', 'nombre' => 'Medidor con sellos manipulados', 'nomenclatura' => 'MCSM'],
            ['encabezados_id' => '3', 'nombre' => 'Medidor con digitos desalineados', 'nomenclatura' => 'MCDD'],
            ['encabezados_id' => '3', 'nombre' => 'Medidor sin talco', 'nomenclatura' => 'MST'],
            ['encabezados_id' => '3', 'nombre' => 'Medidor enterrado', 'nomenclatura' => 'ME'],
            ['encabezados_id' => '3', 'nombre' => 'Conexión directa', 'nomenclatura' => 'CD'],
            ['encabezados_id' => '3', 'nombre' => 'Medidor frenado', 'nomenclatura' => 'MF'],
            ['encabezados_id' => '3', 'nombre' => 'Medidor gira hacia atrás', 'nomenclatura' => 'MGHA'],
            ['encabezados_id' => '3', 'nombre' => 'Medidor No encontrado', 'nomenclatura' => 'MFR'],
            ['encabezados_id' => '3', 'nombre' => 'Medidor No Concuerda con el contrato', 'nomenclatura' => 'MFR'],
            ['encabezados_id' => '3', 'nombre' => 'Medidor trocado', 'nomenclatura' => 'MT'],
            ['encabezados_id' => '3', 'nombre' => 'Inactivo y en Consumo', 'nomenclatura' => 'IC'],
            ['encabezados_id' => '3', 'nombre' => 'Inspecion y revision', 'nomenclatura' => 'IC'],
            ['encabezados_id' => '3', 'nombre' => 'Posible fuga', 'nomenclatura' => 'IC'],
            ['encabezados_id' => '3', 'nombre' => 'pendiente de Retiro / Revision', 'nomenclatura' => 'IC'],
            ['encabezados_id' => '3', 'nombre' => 'Medidor con doble local Comercial', 'nomenclatura' => 'IC'],
            ['encabezados_id' => '4', 'nombre' => 'Restaurante', 'nomenclatura' => 'RE'],
            ['encabezados_id' => '4', 'nombre' => 'Venta de Comidas Rapidas', 'nomenclatura' => 'VCR'],
            ['encabezados_id' => '4', 'nombre' => 'Panaderia', 'nomenclatura' => 'PA'],
            ['encabezados_id' => '4', 'nombre' => 'Cafeteria', 'nomenclatura' => 'CA'],
            ['encabezados_id' => '4', 'nombre' => 'Bar / Discoteca', 'nomenclatura' => 'BA'],
            ['encabezados_id' => '4', 'nombre' => 'Lavanderia', 'nomenclatura' => 'LA'],
            ['encabezados_id' => '4', 'nombre' => 'Venta de Fritos', 'nomenclatura' => 'VF'],
            ['encabezados_id' => '4', 'nombre' => 'Asadero de Pollos', 'nomenclatura' => 'AP'],
            ['encabezados_id' => '4', 'nombre' => 'Industria', 'nomenclatura' => 'IN'],
            ['encabezados_id' => '4', 'nombre' => 'Productor de Quesos / leche', 'nomenclatura' => 'PQL'],
            ['encabezados_id' => '4', 'nombre' => 'Hotel/Motel', 'nomenclatura' => 'HM'],
            ['encabezados_id' => '4', 'nombre' => 'Centro recreacional', 'nomenclatura' => 'CR'],
            ['encabezados_id' => '4', 'nombre' => 'Institucion educativa', 'nomenclatura' => 'IE'],
            ['encabezados_id' => '4', 'nombre' => 'Centro Comercial', 'nomenclatura' => 'FD'],
            ['encabezados_id' => '4', 'nombre' => 'Heladeria', 'nomenclatura' => 'HE'],
            ['encabezados_id' => '4', 'nombre' => 'Bodegas', 'nomenclatura' => 'BO'],
            ['encabezados_id' => '4', 'nombre' => 'Inmueble Desocupado / En Arriendo', 'nomenclatura' => 'IM'],
            ['encabezados_id' => '4', 'nombre' => 'Tienda de Abarrotes', 'nomenclatura' => 'TA'],
            ['encabezados_id' => '4', 'nombre' => 'Ferreteria', 'nomenclatura' => 'TF'],
            ['encabezados_id' => '4', 'nombre' => 'Papeleria y Micelaneas', 'nomenclatura' => 'TP'],
            ['encabezados_id' => '4', 'nombre' => 'Tienda de Juguetes', 'nomenclatura' => 'TJ'],
            ['encabezados_id' => '4', 'nombre' => 'Veterinaria', 'nomenclatura' => 'TM'],
            ['encabezados_id' => '4', 'nombre' => 'Taller de Motos', 'nomenclatura' => 'TB'],
            ['encabezados_id' => '4', 'nombre' => 'Estacion de Servicio', 'nomenclatura' => 'TA'],
            ['encabezados_id' => '4', 'nombre' => 'Hospital / Clinica/ ips / Consultorio', 'nomenclatura' => 'TP'],
            ['encabezados_id' => '4', 'nombre' => 'Terreno Valdio', 'nomenclatura' => 'TV'],
            ['encabezados_id' => '4', 'nombre' => 'Locales Comerciales', 'nomenclatura' => 'TV'],
            ['encabezados_id' => '4', 'nombre' => 'Drogueria', 'nomenclatura' => 'TV'],
            ['encabezados_id' => '4', 'nombre' => 'Edificio / En construccion', 'nomenclatura' => 'TV'],
            ['encabezados_id' => '4', 'nombre' => 'Base Naval / Base Militar', 'nomenclatura' => 'TV'],
            ['encabezados_id' => '4', 'nombre' => 'Comercio no encontrado', 'nomenclatura' => 'TV'],
            ['encabezados_id' => '5', 'nombre' => 'Ninguna', 'nomenclatura' => 'OB'],
            ['encabezados_id' => '5', 'nombre' => 'Obstaculos (Poca Visibilidad)', 'nomenclatura' => 'OB'],
            ['encabezados_id' => '5', 'nombre' => 'Falta de Acceso (Rejas, Cerraduras, Etc)', 'nomenclatura' => 'FA'],
            ['encabezados_id' => '5', 'nombre' => 'Falta de Medidor', 'nomenclatura' => 'FD'],
            ['encabezados_id' => '5', 'nombre' => 'Usuario No Permite Lectura', 'nomenclatura' => 'UNP'],
            ['encabezados_id' => '5', 'nombre' => 'Lugar Deshabitado', 'nomenclatura' => 'LD'],
            ['encabezados_id' => '6', 'nombre' => 'Baja presion', 'nomenclatura' => 'LD'],
            ['encabezados_id' => '6', 'nombre' => 'Media presion', 'nomenclatura' => 'LD'],
            ['encabezados_id' => '6', 'nombre' => 'Alta presion', 'nomenclatura' => 'LD'],
            ['encabezados_id' => '7', 'nombre' => 'DAESUNG', 'nomenclatura' => 'DA'],
            ['encabezados_id' => '7', 'nombre' => 'YAO', 'nomenclatura' => 'YA'],
            ['encabezados_id' => '7', 'nombre' => 'YAZAKI', 'nomenclatura' => 'YA'],
            ['encabezados_id' => '7', 'nombre' => 'GOLDSTAR', 'nomenclatura' => 'GO'],
            ['encabezados_id' => '7', 'nombre' => 'SINGER', 'nomenclatura' => 'SI'],
            ['encabezados_id' => '7', 'nombre' => 'RICOH', 'nomenclatura' => 'RI'],
            ['encabezados_id' => '7', 'nombre' => 'KROHNSCHODER', 'nomenclatura' => 'KR'],
            ['encabezados_id' => '7', 'nombre' => 'AMERICAN METER', 'nomenclatura' => 'AM'],
            ['encabezados_id' => '7', 'nombre' => 'ROCKWELL', 'nomenclatura' => 'RO'],
            ['encabezados_id' => '7', 'nombre' => 'KEUK', 'nomenclatura' => 'KE'],
            ['encabezados_id' => '7', 'nombre' => 'INVENSYS - SENSUS', 'nomenclatura' => 'IN'],
            ['encabezados_id' => '7', 'nombre' => 'ABB ELSTER', 'nomenclatura' => 'AB'],
            ['encabezados_id' => '7', 'nombre' => 'ROMET', 'nomenclatura' => 'RO'],
            ['encabezados_id' => '7', 'nombre' => 'INSTROMET', 'nomenclatura' => 'IN'],
            ['encabezados_id' => '7', 'nombre' => 'IM METER', 'nomenclatura' => 'IM'],
            ['encabezados_id' => '7', 'nombre' => 'ELSTER', 'nomenclatura' => 'EL'],
            ['encabezados_id' => '7', 'nombre' => 'GALLUS', 'nomenclatura' => 'GA'],
            ['encabezados_id' => '7', 'nombre' => 'EQUIMETER', 'nomenclatura' => 'EQ'],
            ['encabezados_id' => '7', 'nombre' => 'ITRON', 'nomenclatura' => 'IT'],
            ['encabezados_id' => '7', 'nombre' => 'ACTARIS', 'nomenclatura' => 'AC'],
            ['encabezados_id' => '7', 'nombre' => 'WILSON', 'nomenclatura' => 'WI'],
            ['encabezados_id' => '7', 'nombre' => '18-KEUK', 'nomenclatura' => '18'],
            ['encabezados_id' => '7', 'nombre' => '12-DAESUNG', 'nomenclatura' => '12'],
            ['encabezados_id' => '7', 'nombre' => '13-ABB ELSTER', 'nomenclatura' => '13'],
            ['encabezados_id' => '7', 'nombre' => '20-IM METER', 'nomenclatura' => '20'],
            ['encabezados_id' => '7', 'nombre' => 'MEDIDOR FICTICIO (CAMBIO) MF', 'nomenclatura' => 'ME'],
            ['encabezados_id' => '7', 'nombre' => '16-INVENSYS - SENSUS', 'nomenclatura' => '16'],
            ['encabezados_id' => '7', 'nombre' => '10-AMERICAN METER', 'nomenclatura' => '10'],
            ['encabezados_id' => '7', 'nombre' => 'KEUKDONG', 'nomenclatura' => 'KE'],
            ['encabezados_id' => '7', 'nombre' => 'INVENSYS-SENSUS', 'nomenclatura' => 'IN'],
            ['encabezados_id' => '7', 'nombre' => 'METREX', 'nomenclatura' => 'ME'],
            ['encabezados_id' => '7', 'nombre' => 'SHINHAN', 'nomenclatura' => 'SH'],
            ['encabezados_id' => '7', 'nombre' => 'GENERICA', 'nomenclatura' => 'GE'],
            ['encabezados_id' => '7', 'nombre' => 'SENSUS', 'nomenclatura' => 'SE'],
            ['encabezados_id' => '7', 'nombre' => 'DRESSER', 'nomenclatura' => 'DR'],
            ['encabezados_id' => '7', 'nombre' => 'DUMIN', 'nomenclatura' => 'DU'],
            ['encabezados_id' => '7', 'nombre' => 'GENERICO', 'nomenclatura' => 'GE'],
            ['encabezados_id' => '7', 'nombre' => '25-FMR', 'nomenclatura' => '25'],
            ['encabezados_id' => '7', 'nombre' => '27-GOLDCAR', 'nomenclatura' => '27'],
            ['encabezados_id' => '7', 'nombre' => 'ITRÓN', 'nomenclatura' => 'IT'],
            ['encabezados_id' => '7', 'nombre' => 'WITECH', 'nomenclatura' => 'WI'],
            ['encabezados_id' => '7', 'nombre' => 'MEDIDOR', 'nomenclatura' => 'ME'],
            ['encabezados_id' => '7', 'nombre' => 'SHINHAN', 'nomenclatura' => 'SH'],
            ['encabezados_id' => '7', 'nombre' => '26-PIETRO', 'nomenclatura' => '26'],
            ['encabezados_id' => '7', 'nombre' => '29-ANCY', 'nomenclatura' => '29'],
            ['encabezados_id' => '7', 'nombre' => 'CHINT', 'nomenclatura' => 'CH'],
            ['encabezados_id' => '7', 'nombre' => '28-SHINHAN', 'nomenclatura' => '28'],
            ['encabezados_id' => '7', 'nombre' => '31-GOLDCARD STS', 'nomenclatura' => '31'],
            ['encabezados_id' => '7', 'nombre' => 'FMG', 'nomenclatura' => 'FM'],
            ['encabezados_id' => '7', 'nombre' => 'TANCY', 'nomenclatura' => 'TA'],
            ['encabezados_id' => '7', 'nombre' => 'GOLDSTAR', 'nomenclatura' => 'GO'],
            ['encabezados_id' => '8', 'nombre' => 'G-1.6', 'nomenclatura' => 'G-'],
            ['encabezados_id' => '8', 'nombre' => 'G-4', 'nomenclatura' => 'G-'],
            ['encabezados_id' => '8', 'nombre' => 'G10', 'nomenclatura' => 'G1'],
            ['encabezados_id' => '8', 'nombre' => 'G16', 'nomenclatura' => 'G1'],
            ['encabezados_id' => '8', 'nombre' => 'G-2.5', 'nomenclatura' => 'G-'],
            ['encabezados_id' => '8', 'nombre' => 'G-16', 'nomenclatura' => 'G-'],
            ['encabezados_id' => '8', 'nombre' => 'G-6', 'nomenclatura' => 'G-'],
            ['encabezados_id' => '8', 'nombre' => 'AL-425', 'nomenclatura' => 'AL'],
            ['encabezados_id' => '8', 'nombre' => 'AL-1000', 'nomenclatura' => 'AL'],
            ['encabezados_id' => '8', 'nombre' => 'AC-630', 'nomenclatura' => 'AC'],
            ['encabezados_id' => '8', 'nombre' => 'AC-250', 'nomenclatura' => 'AC'],
            ['encabezados_id' => '8', 'nombre' => 'AL-800', 'nomenclatura' => 'AL'],
            ['encabezados_id' => '8', 'nombre' => 'MR-8', 'nomenclatura' => 'MR'],
            ['encabezados_id' => '8', 'nombre' => 'MR-10', 'nomenclatura' => 'MR'],
            ['encabezados_id' => '8', 'nombre' => 'MR -12', 'nomenclatura' => 'MR'],

        ];

        foreach ($data as $item) {
            encabezados_dets::create($item);
        }

    }
}
